# Generated by Django 2.2.1 on 2019-06-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publicationDate',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
