# Generated by Django 2.2.1 on 2019-06-17 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20190617_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='book.Book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='book',
            name='publicationDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(verbose_name=range(1, 5)),
        ),
    ]
