# Generated by Django 2.2.1 on 2019-06-17 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0004_auto_20190617_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('author', models.CharField(max_length=128)),
                ('publisher', models.CharField(max_length=128)),
                ('publicationDate', models.DateTimeField()),
                ('price', models.IntegerField()),
            ],
            options={
                'ordering': ['-publicationDate'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=30)),
                ('score', models.IntegerField(verbose_name=range(1, 5))),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
            ],
        ),
    ]
