# Generated by Django 2.2.1 on 2019-06-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20190617_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publicationDate',
            field=models.CharField(max_length=128),
        ),
    ]
