# Generated by Django 2.2.1 on 2019-06-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20190617_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='publicationDate',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.TextField(),
        ),
    ]
