# Generated by Django 2.2.1 on 2019-06-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20190617_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publicationDate',
            field=models.CharField(max_length=20),
        ),
    ]
