# Generated by Django 2.2.1 on 2019-06-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_book_titleno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='titleNo',
        ),
    ]
