# Generated by Django 2.2.1 on 2019-06-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_auto_20190618_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
